permalink: pretty

theme: jekyll_patternbot


patternbot:
  title: "Ceci Bowles"
  description: |
    A small description of who I am and what I do.
  font_url: "https://fonts.googleapis.com/css?family=Montserrat:400,500,700,900&display=swap"
  colors:
    patterns:
      buttons.ghost-white: "--color-primary"
  rationales:
  layouts:
    default: |
      The default layout should be used in every page for the website. It includes the primary header and the footer of the website.
