title: "Footer"
description: |
  The footer of this website should be the final element on every page of the website to navigate the pages, provide location information, get email subscriptions, and link to social media accounts for the website. It should be in the default layout of the website.
